---
# tasks file for motd

- name: Get Fact from api
  uri:
    url: "https://catfact.ninja/fact"
    return_content: yes
    body_format: json
  register: api_result
  run_once: true
  delegate_to: localhost

- name: Copy motd file to remote
  template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444