---

- name: A play with variables
  hosts: webservers
  gather_facts: no

  tasks:

    - name: Setting host facts using set_fact module
      set_fact:
        fact_one: "Hello"
        fact_other: "Bye"
        john_fact: "Doe"

    - name: Print some facts
      debug:
        var: john_fact

    - name: Print some facts
      debug:
        var: fact_other