---

- hosts: webservers
  name: Play with vault
  gather_facts: false

  tasks:

    - name: Load variables
      include_vars: vars.yaml

    - debug:
        msg: "Hello, {{ username }}"

    - debug:
        msg: "Password is {{ password }}"